const BASE_FIELD = Object.freeze({
  selectable: true,
  sortable: true,
  filterable: true,
  fetchable: false,
  omittable: true,
  default: true,
});

const field = (preset, definition) => ({
  ...BASE_FIELD,
  ...preset,
  ...definition,
  ui: { ...(preset.ui || {}), ...(definition.ui || {}) },
  sortOptions: {
    ...(preset.sortOptions || {}),
    ...(definition.sortOptions || {}),
  },
});

const arrayPreset = (items, ui = {}) => ({
  type: `array<${items}>`,
  items,
  selectable: false,
  sortable: false,
  filterable: true,
  fetchable: false,
  omittable: false,
  default: false,
  operators: [
    "IS NONE",
    "IS NOT NONE",
    "CONTAINS",
    "CONTAINSANY",
    "CONTAINSALL",
    "CONTAINSNONE",
  ],
  ui,
});

const PRESETS = Object.freeze({
  string: {
    type: "string",
    operators: [
      "IS NONE",
      "IS NOT NONE",
      "=",
      "!=",
      "?=",
      "STARTS WITH",
      "ENDS WITH",
      "CONTAINS",
      "CONTAINSNOT",
      "IN",
      "NOT IN",
    ],
    sortOptions: { collate: true, numeric: true },
    ui: { input: "text" },
  },
  number: {
    type: "number",
    operators: [
      "IS NONE",
      "IS NOT NONE",
      "=",
      "!=",
      ">",
      "<",
      ">=",
      "<=",
      "IN",
      "NOT IN",
      "INSIDE",
      "OUTSIDE",
    ],
    ui: { input: "number", step: "any" },
  },
  boolean: {
    type: "boolean",
    operators: ["IS NONE", "IS NOT NONE", "=", "!=", "IN", "NOT IN"],
    ui: { input: "boolean" },
  },
  datetime: {
    type: "datetime",
    operators: [
      "IS NONE",
      "IS NOT NONE",
      "=",
      "!=",
      ">",
      "<",
      ">=",
      "<=",
      "IN",
      "NOT IN",
      "INSIDE",
      "OUTSIDE",
    ],
    ui: { input: "datetime-local" },
  },
  record: {
    type: "record",
    operators: ["IS NONE", "IS NOT NONE", "=", "!=", "IN", "NOT IN"],
    ui: { input: "text", placeholder: "table:record-id" },
  },
});

export const USER_CONFIG = Object.freeze({
  domain: "user",
  table: "user",
  ui: {
    title: "USER MANAGEMENT",
    description: "Build a safe, type-aware view of the user domain.",
    entityLabel: "node",
    entityLabelPlural: "nodes",
    pageSizes: [10, 25, 50, 100],
  },
  capabilities: {
    maxLimit: 1000,
    maxFilters: 12,
    maxSorts: 3,
    fetch: true,
    timeout: true,
    parallel: true,
    explain: true,
    omit: true,
  },
  searchable: ["name", "email"],
  fields: [
    field(PRESETS.record, {
      id: "id",
      label: "Node ID",
      select: "id",
      filter: "id",
      sort: "id",
      sortable: false,
      omittable: false,
    }),
    field(PRESETS.string, {
      id: "name",
      label: "Identity Name",
      select: "name",
      filter: "name",
      sort: "name",
      ui: { placeholder: "Search a name" },
    }),
    field(PRESETS.string, {
      id: "email",
      label: "Contact Vector",
      select: "email",
      filter: "email",
      sort: "email",
      operators: [
        "=",
        "!=",
        "STARTS WITH",
        "IN",
        "NOT IN",
        "IS NONE",
        "IS NOT NONE",
      ],
      ui: { input: "email", placeholder: "name@example.com" },
    }),
    field(PRESETS.boolean, {
      id: "login_access",
      label: "Edge Status",
      select: "login_access",
      filter: "login_access",
      sort: "login_access",
    }),
    field(PRESETS.number, {
      id: "dominate_count",
      label: "Sub-Nodes",
      select: "array::len(dominates ?? []) AS dominate_count",
      filter: "array::len(dominates ?? [])",
      sort: "array::len(dominates ?? [])",
    }),
    field(PRESETS.number, {
      id: "parent_count",
      label: "Parent Groups",
      select: "array::len(parents ?? []) AS parent_count",
      filter: "array::len(parents ?? [])",
      sort: "array::len(parents ?? [])",
      default: false,
    }),
    field(PRESETS.number, {
      id: "permission_count",
      label: "Permissions",
      select: "array::len(permissions ?? []) AS permission_count",
      filter: "array::len(permissions ?? [])",
      sort: "array::len(permissions ?? [])",
      default: false,
    }),
    field(PRESETS.datetime, {
      id: "created_at",
      label: "Genesis Date",
      select: "created_at",
      filter: "created_at",
      sort: "created_at",
    }),
    field(PRESETS.datetime, {
      id: "updated_at",
      label: "Last Updated",
      select: "updated_at",
      filter: "updated_at",
      sort: "updated_at",
      default: false,
    }),
    field(arrayPreset("record", { placeholder: "group:one" }), {
      id: "parents",
      label: "Has parent group",
      filter: "parents",
    }),
    field(arrayPreset("record", { placeholder: "user:alice" }), {
      id: "dominates",
      label: "Has sub-node",
      filter: "dominates",
    }),
    field(arrayPreset("string", { placeholder: "read" }), {
      id: "permissions",
      label: "Has permission",
      filter: "permissions",
    }),
    field(PRESETS.record, {
      id: "a_favorite_primitive",
      label: "Fav Primitive",
      select: "a_favorite_primitive",
      filter: "a_favorite_primitive",
      sort: "a_favorite_primitive",
      default: false,
    }),
    field(arrayPreset("record", { placeholder: "user:alice" }), {
      id: "a_friends",
      label: "Friends",
      filter: "a_friends",
    }),
    field(arrayPreset("record", { placeholder: "test_primitive:1" }), {
      id: "a_watched_items",
      label: "Watched Items",
      filter: "a_watched_items",
    }),
  ],
  defaultState: {
    search: "",
    page: 1,
    limit: 10,
    select: [
      "id",
      "name",
      "email",
      "login_access",
      "parent_count",
      "dominate_count",
      "created_at",
    ],
    filters: [],
    sorts: [{ field: "created_at", order: "DESC" }],
    fetch: [],
    options: { timeout: undefined, parallel: false, explain: false, omit: [] },
  },
});
